### ISSUE TITLE
Add Favicon and local assets

### ISSUE THREAD

**Issue by Jorgewlf88** [Hacktoberfest-GYE/hacktoberfestgye-landing#16]
This issue seeks to enhance our project by adding a favicon for a more visually appealing tab icon and improving user experience by incorporating local assets. The task includes designing a favicon that aligns with our brand identity, integrating it into the project, and ensuring it displays correctly across all browsers. Additionally, we aim to replace any existing external asset references with local files to enhance performance and reduce dependency on external hosting. Please consider any best practices for asset management and optimization.

**Comment by bjgavilanes** [comment]
Favicon was added at #17. Closing.

Thank you for everything!,
Brayen.
