### ISSUE TITLE
Add mentors page

### ISSUE THREAD

**Issue by bjgavilanes** [Hacktoberfest-GYE/hacktoberfestgye-landing#19]
We have 3 weeks left for the Hacktoberfest at Guayaquil.

We should have a whole page dedicated for our mentors, that'll provide asistance for Hacktoberfest attendees.

Talking with administrative team, we have acknowledge the need to develop a whole separate site for our mentors.

**Comment by practicatto** [comment]
is there a prototype for this? what is expected from that page?

**Comment by bjgavilanes** [comment]
Greetings!,

No, sorry, there's no prototype. :'(

Webpage should:
- Be a separate page
- Included in navbar, alternative-navbar and footer
- Contain all mentor's relevant information
  - We, as HacktoberfestGYE 2024 team, do have all the information required. We just need the template to upload it.
- html components should be reusable, so we can develop speakers webpage easier

The webpage should be written at `_includes/`; e.g., `_includes/mentors.html`.

@davcortez Can you help us with a prototype? We handle it from there.

**Comment by bjgavilanes** [comment]
Done at #33
