### ISSUE TITLE
Improve the partners section

### ISSUE THREAD

**Issue by jhon-p16** [Hacktoberfest-GYE/hacktoberfestgye-landing#22]
- [x]  Refactor the partners section to use reusable components.
- [x]  Optimize partner logo images to reduce loading times.
- [x]  Ensure all images have descriptive alt attributes.
- [x]  Implement Flexbox or CSS Grid for better alignment and responsiveness.

**Comment by Suvendu-UI** [comment]
can you assign me this issue @jhon-p16 ?

**Comment by bjgavilanes** [comment]
@Suvendu-UI hello! i assigned you, as requested.

#32 handles png optimization.
#25 and #27 the fourth one.

**Comment by Suvendu-UI** [comment]
hey @bjgavilanes how to run the dev server after cloning the repo?

**Comment by bjgavilanes** [comment]
Greetings, @Suvendu-UI ! Thank you for waiting.

I actually recommed you to run `pnpm run dev` at root directory. We do have a Dockerfile and docker-compose, but we are currently in the migration of that toolkit -- this webpage used to be a Jekyll project! --

So, to recap:
- run `pnpm run dev ` at repo root directory
  - Don't forget you should need have installed nodejs and pnpm in your machine, according to your repo.
- make a new branch
- make your changes
- write commits as atomically as posible
- git push origin {new-branch}

And I'll handle from there.

If you need more help, I would be glad to help. Just write me to my mail -- bjgavilanes@gmail.com --, and we'll set up a Meet!

Thank you!

**Comment by bjgavilanes** [comment]
Just to follow up, @Suvendu-UI, #46 added docker support.

I recommend to use "docker-compose up" in root directory.

Let me know if you need help!,
Brayen
