### ISSUE TITLE
Margin at the top of the main section in Mentors page.

### ISSUE THREAD

**Issue by davcortez** [Hacktoberfest-GYE/hacktoberfestgye-landing#39]
## What
Add margin at the top of the main section of the mentors page. This is because, when browsing the page on a mobile device, the section title is not visible as it is covered by the navbar.
![issue-margin](https://github.com/user-attachments/assets/ab2142c3-d9cd-49ab-bdd8-81052d0f585b)

**Comment by bjgavilanes** [comment]
A good way to solve this is see what it's done in /pages/index.astro and what's different.

This is actually a good first issue; a vimdiff and that should be done.

BTW, this is issue is more visible in mobile; but, yeah.

**Comment by bjgavilanes** [comment]
While working in #41 , discovered that behaviour happens because the content -- as in, body html tag -- doesn't have margins defined.

It is, indeed, an easy fix.

**Comment by bjgavilanes** [comment]
#51 closes this.
