### ISSUE TITLE
Margin at the top of main section in Speaker page

### ISSUE THREAD

**Issue by davcortez** [Hacktoberfest-GYE/hacktoberfestgye-landing#40]
## What
Add margin at the top of the main section of the mentors page. This is because, when browsing the page on a mobile device, the section title is not visible as it is covered by the navbar.
![issue-speakers-page](https://github.com/user-attachments/assets/76a9975f-b970-4fc3-bb16-09036e1a32cc)

**Comment by Pariharx7** [comment]
Hey 
I'd like to work on this issue, kindly assign me the issue

**Comment by davcortez** [comment]
Hi @Pariharx7, sure.
@bjgavilanes Do you have any advice?

**Comment by bjgavilanes** [comment]
Yeah!, @Pariharx7, in #39 I stumbled upon a way to fix this issue.

Please, let me know if you need help!,
Brayen

**Comment by Pariharx7** [comment]
Thanks for assigning me the issue. 
I'll try to fix the problem and raise a pr regarding it.

**Comment by bjgavilanes** [comment]
Hello, @Pariharx7!

While working on #49 , I discovered what is causing this behaviour: upper margins -- or padding --, are not defined!

As we use TailwindCSS, you should add a margin or a padding in a div tag, using a class value. Find which one!

Thank you!,
@bjgavilanes

**Comment by Pariharx7** [comment]
ok will work on it
